name: roller_env
channels:
  - defaults
dependencies:
  - python>=3.8
  - pip
  - numpy==1.23.1
  - matplotlib==3.6.2
  - sympy==1.13.3
  # You can add more Conda packages here  
  # - scipy
  - pip:
      - pyglet==2.1.5
      # - another-pip-package